params:
  name: basic_movements_right
  xml_file: './model_files/humanoid_and_basic.xml'
  max_its: 1000
  Tf: 1.0
  t_after: 0
  #optimizer: 'adam'
  #lr: .001
  #lr2: .0005
  # optimizer: 'rmsprop'
  # lr: .05
  # lr2: .05
  optimizer: 'sgd'
  lr: 1e4
  lr2: 1e3
  it_lr2: 800
  grad_update_every: 10
  reset_noise_scale: 0
  incr_every: 10
  t_incr: 0.01
  grab_phase_it: 0
  grad_window_t: 0.1
  #joint_penalty_factor: 1e-6
  # joint_penalty_factor: 1e-12
  joint_penalty_factor: 0
  #balance_cost: 0
  #root_cost: 10
  #joint_cost: 10000
  #foot_cost: 100
  balance_cost: 0
  #balance_cost: 1e10
  root_cost: 1e2
  joint_cost: 5e5
  #joint_cost: 0
  foot_cost: 0
  ctrl_cost: 1
  ctrl_reg_weight: 1e-7
  # ctrl_reg_weight: 0
  mask_decay_factor: 1

