params:
  name: basic_movements_both
  xml_file: './model_files/humanoid_and_basic.xml'
  max_its: 1000
  Tf: 1.0
  t_after: 0
  #optimizer: 'adam'
  #lr: .001
  #lr2: .0005
  optimizer: 'sgd'
  lr: 2.5
  lr2: .5
  it_lr2: 800
  reset_noise_scale: .001
  incr_every: 50
  t_incr: 1.0
  grab_phase_it: 0
  grad_update_every: 10
  grad_window_t: 0.1
  joint_penalty_factor: 5e-7
  balance_cost: 0
  root_cost: 10
  joint_cost: 10000
  foot_cost: 100
  ctrl_cost: 1
