params:
  name: basic_movements_right
  xml_file: './humanoid_and_basic.xml'
  max_its: 1000
  Tf: 1.0
  #optimizer: 'adam'
  #lr: .001
  #lr2: .0005
  optimizer: 'rmsprop'
  lr: .001
  lr2: .0005
  #optimizer: 'sgd'
  #lr: 2.5
  #lr2: .5
  it_lr2: 800
  grad_update_every: 10
  reset_noise_scale: .001
  incr_every: 50
  t_incr: 1.0
  grab_phase_it: 0
  grad_window_t: 0.1
  joint_penalty_factor: 1e-6
  balance_cost: 3000000
  joint_cost: 1000
  foot_cost: 10
  ctrl_cost: 100

