params:
  name: grab_ball
  xml_file: './humanoid_and_baseball.xml'
  Tf: .9
  t_after: 0
  optimizer: 'adam'
  max_its: 500
  lr: .001
  lr2: .0005
  it_lr2: 350
  #optimizer: 'sgd'
  #max_its: 2000
  #lr: 2.5
  #lr2: .5
  #it_lr2: 1500
  grad_update_every: 10
  #reset_noise_scale: .001
  reset_noise_scale: .001
  t_incr: .9
  #t_incr: 1.0
  incr_every: 50
  grab_phase_it: 20
  grad_window_t: 0.1
  joint_penalty_factor: 1e-6
  balance_cost: 6000
  joint_cost: 200
  foot_cost: 6000
  ctrl_cost: 100
  root_cost: 10
