params:
  name: tennis_serve
  xml_file: './model_files/humanoid_and_tennis.xml'
  Tf: 1.8
  t_after: .8
  max_its: 3000
  optimizer: 'adam'
  lr: .2
  lr_2: .2
  # it_lr2: 350
  # optimizer: 'rmsprop'
  # lr: 0.02
  # lr2: 0.02
  # optimizer: 'sgd'
  # lr: 2e5
  # lr2: 1
  it_lr_2: 3000
  # it_lr_2: 6000
  grad_update_every: 10
  reset_noise_scale: 0
  t_incr: .1
  # t_incr_2: .1
  t_incr_2: .05
  incr_every: 150
  # incr_every: 300
  # incr_every: 750
  # incr_every_2: 750
  incr_every_2: 150
  grab_phase_it: 600
  # grab_phase_it: 1200
  # grab_phase_it: 3000
  grab_phase_t: .4
  grad_window_t: .05
  mask_window_t: .25
  # joint_penalty_factor: 1e-6
  # balance_cost: 6000
  # joint_cost: 200
  # foot_cost: 6000
  # ctrl_cost: 100
  # root_cost: 10
  joint_penalty_factor: 1e-6
  balance_cost: 0
  root_cost: 2e3
  joint_cost: 8e6
  foot_cost: 0
  ctrl_cost: 1
  # ctrl_reg_weight: 1e-6
  ctrl_reg_weight: 0
  q_pos_weight: 1e-6
  mask_decay_factor: .9
