params:
  name: tennis_serve
  xml_file: './humanoid_and_tennis.xml'
  Tf: 1.8
  #optimizer: 'adam'
  #lr: .0005
  #lr2: .0005
  #it_lr2: 800
  optimizer: 'adam'
  max_its: 1000
  lr: .0005
  lr2: .0005
  it_lr2: 800
  grad_update_every: 10
  reset_noise_scale: .001
  t_incr: 1.8
  incr_every: 50
  grab_phase_it: 40
  grad_window_t: .1
  joint_penalty_factor: 1e-6
  #balance_cost: 1000
  #joint_cost: 500
  balance_cost: 4000
  joint_cost: 200
  foot_cost: 6000
  ctrl_cost: 100

