params:
  name: tennis_grab
  xml_file: './humanoid_and_tennis.xml'
  max_its: 500
  Tf: 1.8
  #optimizer: 'adam'
  #lr: .001
  #lr2: .0005
  optimizer: 'sgd'
  lr: 2.5
  lr2: .5
  it_lr2: 350
  grad_update_every: 10
  reset_noise_scale: .001
  t_incr: 1.8
  incr_every: 50
  grab_phase_it: 20
  grad_window_t: 0.1
  joint_penalty_factor: 5e-7
  balance_cost: 6000
  joint_cost: 200
  foot_cost: 6000
  ctrl_cost: 10
