params:
  name: tennis_serve
  xml_file: './humanoid_and_tennis.xml'
  Tf: 1.8
  #optimizer: 'adam'
  #lr: .0005
  #lr2: .0005
  #it_lr2: 800
  #optimizer: 'adam'
  optimizer: 'rmsprop'
  max_its: 100
  #lr: .0005
  lr: .005
  #lr2: .0005
  lr2: .005
  it_lr2: 800
  grad_update_every: 10
  #grad_update_every: 1
  reset_noise_scale: .001
  t_incr: 1.8
  incr_every: 50
  #grab_phase_it: 20
  grab_phase_it: 3
  #grad_window_t: .1
  grad_window_t: 0.1
  joint_penalty_factor: 1e-2
  #balance_cost: 1000
  #joint_cost: 500
  balance_cost: 30000
  joint_cost: 600
  foot_cost: 9000
  ctrl_cost: 100

